---
- name: Create db for app
  mysql_db:
   name: "{{ mysql_db_name }}"
   state: present

- name: Create MYSQL user
  mysql_user:
   name: "{{ mysql_user_name }}"
   password: "{{ mysql_user_password }}"
   priv: "{{ mysql_db_name }}.*:ALL"
   host: '%'
   state: present

