---
 - name: Deploy Gogs with DB
   hosts: db
   become: yes

   tasks:
    - name: Install MySQL and dependencies
      apt:
       name: "{{item}}"
       state: present
       update_cache: yes
      loop:
       - mysql-server
       - mysql-client
       - python-mysqldb


    - name: start and enable Mysql
      service:
       name: mysql
       state: started
       enabled: yes

    - name: Create database for Gogs
      mysql_db: 
       name: gogs
       state: present

    - name: Create Mysql user for gogs
      mysql_user:
       name: {{ db_user }}
       password: gogs
       priv: "{{db_user}}.*:ALL" 
       state: present

 - name: Install and Configure Gogs
   hosts: app
   become: yes

   tasks:
    - name: Install dependencies
      apt:
       name:
        - git
        - zip
        - unzip
       state: latest

    - name: Install Gogs
      shell: |
       wget https://dl.gogs.io/0.12.11/gogs_0.12.11_linux_amd64.zip
       unzip gogs_0.12.11_linux_amd64.zip
       mv gogs /home/vagrant

    - name: Ensure  Gogs dir exists
      file:
       path: /home/vagrant
       state: directory
       owner : vagrant
       group: vagrant

    - name: Create dir for confFile
      shell: | 
       cd /home/vagrant/gogs
       mkdir custom
       mkdir conf
       touch app.ini

    - name: Conf file  
      copy:
       content:
        [database]
        DB_TYPE = mysql
        HOST = hostvars[db]['ansible_enp0s8']['ipv4']['address']:5432
        NAME = gogs
        USER = gogs
        PASSWORD = gogs
       dest: /home/vagrant/gogs/custom/conf/app.ini

    - name: Start Gogs
      shell: | 
       cd /home/vagrant/gogs
       ./gogs web






