 - name: Setting DB
   hosts: db
   become: yes
   roles:
    - db_role

 - name: Setting App
   hosts: app
   become: yes
   roles:
    - app_role

 - name : Setting Nginx
   hosts: nginx
   become: yes
   roles: 
    - nginx_role
