- name : Update cache on all machine
   hosts: all
   become : yes
   remote_user: vagrant
   roles : 
    - common_role

- name: Setting DB
   hosts: db
   become: yes
   remote_user: vagrant
   roles:
    - db_role

 - name: Setting App
   hosts: app
   become: yes
   remote_user: vagrant
   roles:
    - app_role


# - name : Setting Nginx
#   hosts: nginx
#   become: yes
#   remote_user: vagrant
#   roles: 
#    - nginx_role
