---
- name: Create systemd-service for Gogs
  template:
   src: gogs_service.j2
   dest: /etc/systemd/system/gogs.service
   mode: '0644'

- name: Reload systemd
  systemd:
    deamon_reload: yes      

- name: Active Gogs as service
  systemd:
    name: gogs
    enabled: yes
    state: restarted
  notify: Restart Gogs

