---
# tasks file for app_role

- name: Update cache OS
  apt:
   update_cache: yes

- name: Install dependencies
  apt:
    name:
     - git
     - zip
     - unzip
    state: latest

- name: Transfer Gogs archive from Ansible Controller to linux1
  copy:
    src: /tmp/gogs.zip
    dest: /tmp/gogs.zip
    mode: '0644'

- name: Copy Gogs from MasterNode
  copy:
   src: /tmp/gogs.zip
   dest:  "{{ vagrant_dest }}/"
   mode: '0644'
   remote_src : yes

- name: Extract Gogs
  unarchive:
   src:  "{{ vagrant_dest }}/gogs.zip"
   dest:  "{{ vagrant_dest }}/"
   remote_src: yes

- name: Ensure Gogs directory exists
  file:
    path: /home/vagrant/gogs
    state: directory
    owner: vagrant
    group: vagrant
    recurse: yes

- name: Create dir for Conf
  file:
   path: /home/vagrant/gogs/custom/conf
   state: directory
   owner: vagrant
   group: vagrant
   mode: '0755'

- name: Create app.ini file
  file:
    path: /home/vagrant/gogs/custom/conf/app.ini
    state: touch
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Configure App.ini file
  template:
   src: gogs_config.j2
   dest: "{{ vagrant_dest }}/gogs/custom/conf/app.ini"

- name: Create systemd-service for Gogs
  template:
   src: gogs_service.j2
   dest: /etc/systemd/system/gogs.service
   mode: '0644'

- name: Reload systemd
  command: sudo systemctl daemon-reload

- name: Active Gogs as service
  systemd:
    name: gogs
    enabled: yes
    state: restarted
  notify: Restart Gogs

  
